language:
  - python
  - node_js

# test using these versions of python
python:
  - "2.6"
  - "2.7"
  - "pypy"

# test using these versions of javascript
node_js:
  - "0.11"
  - "0.10"

# command to install dependencies
install:
  - pip install -q -r scripts/requirements.txt --extra-index-url https://pypi.crate.io/simple/
  - npm install production

addons:
  firefox: "31.1"

# setup mysql
before_script:
  - FIREFOX_BIN=/usr/bin/firefox
  - mysql -e 'create database gateway;'
  - mysqladmin -u root password "root"
  - python manage.py syncdb --noinput
  - python manage.py loaddata fixture/venture.yaml

# command to run tests
script:
  - pep8 .  --exclude bootstrap
  - karma start --single-run --browsers Firefox
  - jshint .
  - radon cc manage.py test
  - radon mi manage.py test
  - coverage run --source gateway manage.py test gateway.tests

after_success:
  - coveralls

matrix:
  allow_failures:
    - python: "pypy"
