language: python
#test using these versions of python
python:
  - "2.6"
  - "2.7"
  - "pypy"

# command to install dependencies
install:
  - pip install -q -r scripts/requirements.txt --extra-index-url https://pypi.crate.io/simple/
  - npm install production

# setup mysql
before_script:
  - mysql -e 'create database gateway;'
  - mysqladmin -u root password "root"
  - python manage.py syncdb --noinput
  - python manage.py loaddata fixture/venture.yaml

# command to run tests
script:
  - pep8 .  --exclude bootstrap
  - npm test
  - radon cc manage.py test
  - radon mi manage.py test
  - coverage run --source gateway manage.py test gateway.tests

after_success:
  - coveralls

matrix:
  allow_failures:
    - python: "pypy"
